# Use postgres/example user/password credentials
version: '3.3'

services:

  db:
    image: postgres:11.6
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespwd
      POSTGRES_DB: jakartaee_petclinic
      CHARSET: UTF8
      PGPORT: 5432

  dbtest:
    image: postgres:11.6
    restart: always
    ports:
      - 5464:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespwd
      POSTGRES_DB: jakartaee_petclinic_test
      CHARSET: UTF8
      PGPORT: 5464

  adminer:
    image: adminer:4.7.4
    restart: always
    ports:
      - 4000:8080

  openliberty:
    image: open-liberty:javaee8
    restart: always
    ports:
      - 80:9080
      - 443:9443
